import { AlertTriangle, ArrowUpRight, BedDouble, Clock3, UsersRound } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip } from 'recharts';
import { motion } from 'framer-motion';

const flow = [{ h: '06', v: 53 }, { h: '08', v: 67 }, { h: '10', v: 61 }, { h: '12', v: 78 }, { h: '14', v: 71 }, { h: '16', v: 84 }];
const metrics = [{ label: 'Hospital occupancy', value: '82.4%', delta: '+2.8%', icon: BedDouble, tone: 'text-cyan-300' }, { label: 'ER queue', value: '18', delta: '3 high priority', icon: UsersRound, tone: 'text-amber-300' }, { label: 'Average wait time', value: '34m', delta: '↓ 6 min today', icon: Clock3, tone: 'text-emerald-300' }];

export function CommandCenterPage() {
  return <div className="mx-auto max-w-7xl p-5 lg:p-8"><section className="grid gap-4 md:grid-cols-3">{metrics.map(({ label, value, delta, icon: Icon, tone }, index) => <motion.article key={label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .08 }} className="glass-panel rounded-2xl p-5"><div className="flex items-start justify-between"><span className="text-sm text-slate-400">{label}</span><Icon className={tone} size={20}/></div><div className="mt-5 flex items-end justify-between"><strong className="text-3xl font-semibold tracking-tight">{value}</strong><span className={'text-xs font-medium ' + tone}>{delta}</span></div></motion.article>)}</section><section className="mt-5 grid gap-5 lg:grid-cols-[1.45fr_1fr]"><article className="glass-panel rounded-2xl p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Patient flow velocity</h2><p className="mt-1 text-sm text-slate-400">Admission and discharge throughput — today</p></div><span className="inline-flex items-center gap-1 text-sm text-emerald-300"><ArrowUpRight size={15}/> 14.2%</span></div><div className="mt-8 h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={flow}><defs><linearGradient id="flow" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2589f4" stopOpacity={.45}/><stop offset="100%" stopColor="#2589f4" stopOpacity={0}/></linearGradient></defs><Tooltip contentStyle={{ background: '#0b1829', border: '1px solid rgba(148,163,184,.14)', borderRadius: 10 }} labelStyle={{ color: '#94a3b8' }} /><Area type="monotone" dataKey="v" stroke="#52b8ff" strokeWidth={2.5} fill="url(#flow)" /></AreaChart></ResponsiveContainer></div></article><article className="glass-panel rounded-2xl p-6"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-amber-400/10 text-amber-300"><AlertTriangle size={18}/></span><div><h2 className="font-semibold">Priority interventions</h2><p className="text-sm text-slate-400">Requires attention</p></div></div><div className="mt-6 space-y-3">{['ICU reaches 90% capacity in 42 minutes', 'Three discharge-ready patients need review', 'Emergency intake surge projected at 17:00'].map((item, index) => <div key={item} className="rounded-xl border border-line bg-white/[.025] p-3"><p className="text-sm text-slate-200">{item}</p><p className="mt-1 text-xs text-slate-500">Priority {index + 1} · AI signal</p></div>)}</div></article></section></div>;
}
