import { ArrowRight, BarChart3, BrainCircuit, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';

const pillars = [{ icon: BarChart3, title: 'Live operational clarity', text: 'Turn fragmented capacity signals into a decisive command center.' }, { icon: BrainCircuit, title: 'Predictive intelligence', text: 'Surface risks before bottlenecks cascade through the hospital.' }, { icon: ShieldCheck, title: 'Enterprise by design', text: 'Secure, auditable foundations built for clinical operations.' }];

export function LandingPage() {
  return <main className="overflow-hidden"><nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link to="/" className="flex items-center gap-3 font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-500 shadow-lg shadow-brand-500/30">M</span>MediFlow</Link><div className="flex items-center gap-2"><Link to="/login"><Button variant="ghost">Sign in</Button></Link><Link to="/app"><Button>Request demo</Button></Link></div></nav><section className="mx-auto max-w-5xl px-6 pb-24 pt-20 text-center lg:pt-28"><motion.p initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="mb-6 text-sm font-medium text-cyan-300">HOSPITAL OPERATIONS INTELLIGENCE</motion.p><motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }} className="text-balance text-5xl font-semibold tracking-tight text-white sm:text-7xl">Make hospital flow <span className="text-brand-400">predictable.</span></motion.h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-400">MediFlow gives operations leaders a live, intelligent view of capacity, patient flow, and the interventions that prevent tomorrow’s bottlenecks.</p><div className="mt-10 flex justify-center gap-3"><Link to="/app"><Button className="gap-2">Explore command center <ArrowRight size={16}/></Button></Link><Button variant="secondary">Talk to our team</Button></div></section><section className="mx-auto grid max-w-6xl gap-4 px-6 pb-20 md:grid-cols-3">{pillars.map(({ icon: Icon, title, text }, index) => <motion.article key={title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: index * .08 }} viewport={{ once: true }} className="glass-panel rounded-2xl p-6"><span className="mb-5 grid h-10 w-10 place-items-center rounded-lg bg-brand-500/15 text-brand-400"><Icon size={20}/></span><h2 className="font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></motion.article>)}</section></main>;
}
